version: '3.8'
services:
  frontend:
    build: ./docker/development
    container_name: frontend_dev
    restart: always
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "3000:80"
